name: Run system tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_system_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run the system tests
        run: ./docker/rpms/build-and-install-rpms.sh --with-system-tests el8 docker/rpms/CentOS_8/CentOS8.dockerfile
